window.MeitivData = {
  categories: ['All', 'Meat & Poultry', 'Dairy', 'Pantry', 'Bakery', 'Frozen', 'Produce', 'Beverages & Drinks'],
  hashgachas: ['All', 'Vaad Hakashrus KY', 'Volova', 'Hisachdus (CRC)', 'Weissmandel', 'Badatz', 'Nirbater'],
  products: [
    {
      id: '1',
      name: 'Mehadrin Chocolate Leben',
      category: 'Dairy',
      hashgacha: 'VolovoOU',
      price: 3.49,
      unit: 'lb',
      bulkDeal: 'Case of 12: $9.99',
      kosherForPassover: true,
      image: 'https://www.kroger.com/product/images/xlarge/front/0001435310005',
      description: 'Mehadrin Chocolate Leben Family Pack, 12 ct / 6 oz.',
      featured: true,
    },
    {
      id: '2',
      name: 'Gefen Canola Oil',
      category: 'Beverages & Drinks',
      hashgacha: 'Volova',
      price: 4.99,
      unit: 'gallon',
      bulkDeal: 'Buy 4 get 1 Free',
      kosherForPassover: true,
      image: 'https://groceryeshop.us/cdn/shop/files/81gIH5wEa8L.jpg?v=1767335107&width=1946&fit=crop&q=80',
      description: 'Gefen Canola Oil 96oz.',
      featured: true,
    },
    {
      id: '3',
      name: 'Bulk Matzah (Hand Shmura)',
      category: 'Bakery',
      hashgacha: 'Vaad Hakashrus KY',
      price: 34.99,
      unit: 'lb',
      bulkDeal: '3 lbs for $99',
      kosherForPassover: true,
      image: 'https://cdn11.bigcommerce.com/s-xermqxgrmv/images/stencil/500x659/products/217/567/KJ1__23593.1768452013.png?c=1',
      description: 'Kiryas Yoel hand-baked Shmura Matzah for Pesach.',
      featured: true,
    },
    {
      id: '4',
      name: 'Gefilte Fish Loaf',
      category: 'Frozen',
      hashgacha: 'Hisachdus (CRC)',
      price: 6.99,
      unit: '20 oz',
      bulkDeal: 'Case of 12: $80',
      kosherForPassover: true,
      image: 'https://d226b0iufwcjmj.cloudfront.net/product-images/global/176076/11938772/large.jpg',
      description: 'Classic frozen gefilte fish, ready to boil.',
    },
    {
      id: '5',
      name: 'Kosher Grape Juice',
      category: 'Pantry',
      hashgacha: 'OU',
      price: 5.49,
      unit: '64 oz',
      bulkDeal: 'Case of 8: $30',
      kosherForPassover: true,
      image: 'https://groceryeshop.us/cdn/shop/files/81gIH5wEa8L.jpg?v=1767335107&width=1946&fit=crop&q=80',
      description: 'Kedem 100% pure concord grape juice. Mevushal.',
      featured: true,
    },
    {
      id: '6',
      name: 'Challah (Water)',
      category: 'Bakery',
      hashgacha: 'OK',
      price: 4.50,
      unit: 'loaf',
      bulkDeal: '3 for $12',
      kosherForPassover: false,
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800',
      description: 'Freshly baked traditional water challah for Shabbat.',
    },
    {
      id: '7',
      name: 'Kosher Salt (Coarse)',
      category: 'Pantry',
      hashgacha: 'OU',
      price: 2.99,
      unit: '3 lb box',
      bulkDeal: 'Case of 12: $30',
      kosherForPassover: true,
      image: 'https://images.unsplash.com/photo-1626014903706-53801261f214?auto=format&fit=crop&q=80&w=800',
      description: 'Coarse kosher salt, perfect for cooking and kashering meat.',
    },
    {
      id: '8',
      name: 'Sliced Pastrami',
      category: 'Meat & Poultry',
      hashgacha: 'Star-K',
      price: 14.99,
      unit: 'lb',
      bulkDeal: '5 lbs for $65',
      kosherForPassover: false,
      image: 'https://images.unsplash.com/photo-1628268909376-e8c4df39c1e7?auto=format&fit=crop&q=80&w=800',
      description: 'Premium sliced deli pastrami. Glatt Kosher.',
    },
    {
      id: '9',
      name: 'Israeli Couscous',
      category: 'Pantry',
      hashgacha: 'OU',
      price: 3.99,
      unit: '16 oz',
      bulkDeal: 'Case of 12: $42',
      kosherForPassover: false,
      image: 'https://images.unsplash.com/photo-1596568359553-b4d2417b116c?auto=format&fit=crop&q=80&w=800',
      description: 'Authentic toasted pasta pearls from Israel.',
    },
    {
      id: '10',
      name: 'Frozen Cheese Blintzes',
      category: 'Frozen',
      hashgacha: 'Badatz',
      price: 6.99,
      unit: '6 pack',
      bulkDeal: 'Buy 3 get 1 Free',
      kosherForPassover: false,
      image: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?auto=format&fit=crop&q=80&w=800',
      description: 'Sweet cheese filled crepes, perfect for Shavuot or breakfast.',
    },
    {
      id: '11',
      name: 'Fresh Persian Cucumbers',
      category: 'Produce',
      hashgacha: 'OU',
      price: 1.99,
      unit: 'lb',
      bulkDeal: '10 lb box: $15',
      kosherForPassover: true,
      image: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&q=80&w=800',
      description: 'Crisp, mini cucumbers perfect for Israeli salad.',
    },
    {
      id: '12',
      name: 'Bamba Peanut Snack',
      category: 'Pantry',
      hashgacha: 'Badatz',
      price: 1.25,
      unit: '1 oz bag',
      bulkDeal: 'Case of 24: $24',
      kosherForPassover: false,
      image: 'https://images.unsplash.com/photo-1599598425947-33002629ee8f?auto=format&fit=crop&q=80&w=800',
      description: 'Classic Israeli peanut butter puff snack.',
    }
  ]
};
